#cloud-config # Cloud-Config-Datei

users: # Benutzerkonfiguration
  - name: ubuntu # Benutzername: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL # Vollzugriffsrechte ohne Passwortabfrage
    groups: users, admin # Mitglied in den Gruppen 'users' und 'admin'
    home: /home/ubuntu # Home-Verzeichnis des Benutzers
    shell: /bin/bash # Standard-Shell für den Benutzer
    ssh_authorized_keys: # SSH-Schlüssel für den Benutzer
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD # Öffentlicher SSH-Schlüssel für den Benutzer
ssh_pwauth: false # Passwortauthentifizierung für SSH deaktivieren
disable_root: false # Root-Login ist aktiviert
package_update: true # Aktualisieren der Paketquellen
packages: # Zu installierende Pakete
  - curl # curl-Paket
  - wget # wget-Paket
